"""Seed sample luxury product data on first run."""
from datetime import datetime, timezone
import uuid

SAMPLE_PRODUCTS = [
    {
        "name": "Noir Automatic 42",
        "sku": "LUM-NA-42",
        "category": "Watches",
        "price": 4890.00,
        "compare_at_price": 6200.00,
        "currency": "USD",
        "short_description": "Swiss automatic movement encased in brushed obsidian steel.",
        "description": "The Noir Automatic 42 is a self-winding chronometer with a 72-hour power reserve, sapphire crystal, and hand-finished obsidian dial. Water resistant to 100m.",
        "images": [
            "https://images.pexels.com/photos/12157290/pexels-photo-12157290.jpeg",
            "https://images.pexels.com/photos/15019856/pexels-photo-15019856.jpeg",
        ],
        "tags": ["automatic", "swiss", "steel", "men"],
        "specs": {"Movement": "Swiss Automatic", "Case": "42mm Steel", "Water Resistance": "100m", "Warranty": "5 years"},
        "stock": 12,
        "featured": True,
        "rating": 4.8,
        "review_count": 24,
    },
    {
        "name": "Éclat Chronograph Gold",
        "sku": "LUM-EC-38",
        "category": "Watches",
        "price": 7250.00,
        "compare_at_price": None,
        "currency": "USD",
        "short_description": "18k gold-plated chronograph with tachymeter bezel.",
        "description": "A refined chronograph paired with a hand-stitched Italian leather strap. Featuring three sub-dials and a date complication.",
        "images": [
            "https://images.unsplash.com/photo-1633869699811-cd4f63049b36",
            "https://images.unsplash.com/photo-1633869701352-eb7af08a1bc4",
        ],
        "tags": ["chronograph", "gold", "leather"],
        "specs": {"Movement": "Quartz Chronograph", "Case": "38mm 18k Gold Plated", "Strap": "Italian Leather"},
        "stock": 6,
        "featured": True,
        "rating": 4.9,
        "review_count": 18,
    },
    {
        "name": "Onyx Signet Ring",
        "sku": "LUM-OS-01",
        "category": "Jewelry",
        "price": 1290.00,
        "compare_at_price": None,
        "currency": "USD",
        "short_description": "Solid sterling silver with polished onyx inlay.",
        "description": "Hand-forged signet ring set with a genuine black onyx stone. Available in sizes 6-13.",
        "images": [
            "https://images.pexels.com/photos/4862863/pexels-photo-4862863.jpeg",
        ],
        "tags": ["silver", "ring", "onyx"],
        "specs": {"Material": "Sterling Silver 925", "Stone": "Black Onyx", "Finish": "Polished"},
        "stock": 20,
        "featured": False,
        "rating": 4.6,
        "review_count": 11,
    },
    {
        "name": "Velour Weekender Bag",
        "sku": "LUM-VB-01",
        "category": "Leather Goods",
        "price": 2150.00,
        "compare_at_price": 2500.00,
        "currency": "USD",
        "short_description": "Full-grain Italian leather with brass hardware.",
        "description": "A weekend companion crafted from vegetable-tanned full-grain leather. Interior features a padded laptop sleeve and three utility pockets.",
        "images": [
            "https://images.unsplash.com/photo-1553062407-98eeb64c6a62",
        ],
        "tags": ["leather", "travel", "unisex"],
        "specs": {"Material": "Full-grain leather", "Hardware": "Solid brass", "Dimensions": "50 x 30 x 25 cm"},
        "stock": 8,
        "featured": True,
        "rating": 4.7,
        "review_count": 32,
    },
    {
        "name": "Meridian Fountain Pen",
        "sku": "LUM-MP-01",
        "category": "Writing",
        "price": 780.00,
        "compare_at_price": None,
        "currency": "USD",
        "short_description": "Rhodium-plated 18k gold nib with piston filler.",
        "description": "Handcrafted resin barrel with a rhodium-plated 18k gold nib. Comes in a lacquered presentation case.",
        "images": [
            "https://images.unsplash.com/photo-1583485088034-697b5bc36b92",
        ],
        "tags": ["pen", "writing", "gold-nib"],
        "specs": {"Nib": "18k Gold Rhodium-plated", "Filler": "Piston", "Barrel": "Precious resin"},
        "stock": 15,
        "featured": False,
        "rating": 4.9,
        "review_count": 9,
    },
    {
        "name": "Aria Silk Scarf",
        "sku": "LUM-AS-01",
        "category": "Accessories",
        "price": 340.00,
        "compare_at_price": None,
        "currency": "USD",
        "short_description": "Hand-rolled 100% mulberry silk twill.",
        "description": "Printed in Como, Italy on premium 16-momme mulberry silk. Hand-rolled edges.",
        "images": [
            "https://images.unsplash.com/photo-1601924994987-69e26d50dc26",
        ],
        "tags": ["silk", "scarf", "women"],
        "specs": {"Material": "100% Mulberry Silk", "Dimensions": "90 x 90 cm", "Origin": "Made in Italy"},
        "stock": 30,
        "featured": False,
        "rating": 4.5,
        "review_count": 14,
    },
    {
        "name": "Astral Cufflinks",
        "sku": "LUM-AC-01",
        "category": "Jewelry",
        "price": 620.00,
        "compare_at_price": None,
        "currency": "USD",
        "short_description": "Rhodium-finished with lab-grown sapphire centers.",
        "description": "Precision-milled cufflinks with hand-set lab-grown sapphires. Toggle-back closure.",
        "images": [
            "https://images.unsplash.com/photo-1611652022419-a9419f74343d",
        ],
        "tags": ["cufflinks", "sapphire"],
        "specs": {"Material": "Rhodium-plated brass", "Stone": "Lab-grown sapphire"},
        "stock": 22,
        "featured": False,
        "rating": 4.7,
        "review_count": 6,
    },
    {
        "name": "Sable Card Wallet",
        "sku": "LUM-SW-01",
        "category": "Leather Goods",
        "price": 290.00,
        "compare_at_price": 360.00,
        "currency": "USD",
        "short_description": "Slim bi-fold in supple calfskin.",
        "description": "Six card slots and two bill compartments in beautifully patina-ing calfskin.",
        "images": [
            "https://images.unsplash.com/photo-1627123424574-724758594e93",
        ],
        "tags": ["wallet", "leather"],
        "specs": {"Material": "Calfskin", "Card slots": "6", "Colors": "Sable, Onyx"},
        "stock": 40,
        "featured": True,
        "rating": 4.6,
        "review_count": 22,
    },
]


def build_seed_docs():
    now = datetime.now(timezone.utc).isoformat()
    docs = []
    for p in SAMPLE_PRODUCTS:
        docs.append({
            "id": str(uuid.uuid4()),
            **p,
            "created_at": now,
            "updated_at": now,
        })
    return docs
